### ISSUE TITLE
Listing on bosh.io page?

### ISSUE THREAD

**Issue by aegershman** [making/nexus-boshrelease#15]
Do you have any intent to try to get this listed on the [Bosh.io](https://bosh.io/releases#submit-a-release) community releases page? 

Thanks a ton for your work!

EDIT: For our purposes, we're going to use the github-release resource to pull down your release & use it in our deployment pipeline.

**Comment by xyloman** [comment]
I am working with @aegershman and we are evaluating using the concourse bosh-io resource: https://github.com/concourse/bosh-io-release-resource which would simplify the continuous delivery of our nexus deployment.  The concourse resource will pull the release from bosh.io if it is registered here: https://github.com/bosh-io/releases/blob/master/index.yml  It appears that most of the boxes have been checked in order for this to work since it appears that most of the blob bits are upload to the cloud foundry community s3 bucket already.
